### PR TITLE
Remove print messages

### PR DESCRIPTION
**Pull request by gpambrozio**
Seems inappropriate for a library and when running my code I was wondering where it was coming from.

### CODE REVIEW

**Comment by alexbarcelo** [comment]
Some quick & dirty testing on my side that ended up in a commit and I overlooked. Sorry and thank you!

**Comment by gpambrozio** [comment]
Thank you for creating this and making my life easier @alexbarcelo. Do you plan to do a release with the fix so pip can pick it up?

**Comment by alexbarcelo** [comment]
Given that it was only a minor log issue and only affected the fan and there are no other commits on the backlog, I was gonna wait a while before doing a new release.

Remember that, meanwhile, you can still use pip by using the git directly, i.e.:

`pip install git+https://github.com/alexbarcelo/hass-mqtt-things.git`

Does that work for you? I mean, I can do a release but...

**Comment by gpambrozio** [comment]
Yeah, I just thought about that too so really no need, thanks.

**Pull request merged**
